auth_url = "https://iam.eu-nl.otc.t-systems.com:443/v3"
region = "eu-nl"
project_name = "eu-nl"
availability_zone = "eu-nl-01"
otc_image_name = "packer-image-ubuntu"
flavor = "c4.xlarge.2"
ssh_username = "ubuntu"
source_image_name = "Standard_Ubuntu_22.04_latest"